### ISSUE TITLE
Terminating app due to uncaught exception 'NSInvalidArgumentException'

### ISSUE THREAD

**Issue by joew8** [wsvn53/scrcpy-mobile#45]
Hi, I use an iPhone 13 pro max (iOS 16.1) to connect with an Android 12 device.  It doesn't work after "Scrcpy Connected" shows. Here's the log.

> check thread 0x0 status 0
> cleaning 1/1 threads
> thread count after clean: 0
> thread: pid=7563, name=ADB-7563 started.
> adb -s 192.168.1.10:5555 shell CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 2.0 scid=154979dc log_level=debug video_bit_rate=4000000 audio_bit_rate=128000 video_codec=h265 max_fps=60 tunnel_forward=true stay_awake=true
> scrcpy-server app_process started
DEBUG: Remaining connection attempts: 100
2023-11-11 20:00:39.075 scrcpy-ios[961:25795030] -> Send command to trigger video restart I frame
2023-11-11 20:00:39.076 scrcpy-ios[961:25795030] -> Syncing clipboard
2023-11-11 20:00:39.076 scrcpy-ios[961:25795030] CLIPBOARD EVENT: Post Success
DEBUG: Remaining connection attempts: 99
> check thread 0x16b1d67e8 status 0
> cleaning 0/1 threads
> thread count after clean: 1
> thread: pid=6120, name=ADB-6120 started.
> adb -s 192.168.1.10:5555 forward --remove tcp:27183
> pid=6120, success=true
> result:

DEBUG: Server connected
DEBUG: Starting controller thread
DEBUG: Starting receiver thread
DEBUG: Receiver stopped
* daemon not running; starting now at tcp:15037
scrcpy-ios I 11-11 20:00:22   961 25794791 auth.cpp:417] adb_auth_init...
scrcpy-ios I 11-11 20:00:22   961 25794791 auth.cpp:220] User key '/var/mobile/Containers/Data/Application/AF213A1E-E91A-4279-B69D-17C350AF5D95/Documents/.android/adbkey' does not exist...
scrcpy-ios I 11-11 20:00:22   961 25794791 auth.cpp:64] generate_key(/var/mobile/Containers/Data/Application/AF213A1E-E91A-4279-B69D-17C350AF5D95/Documents/.android/adbkey)...
scrcpy-ios I 11-11 20:00:22   961 25794791 auth.cpp:152] loaded new key from '/var/mobile/Containers/Data/Application/AF213A1E-E91A-4279-B69D-17C350AF5D95/Documents/.android/adbkey' with fingerprint 560B4F75E9950ECB1F7715BFA40617B19A2B73B0500CA92FD75D567199F1D6DD
* daemon started successfully
scrcpy-ios I 11-11 20:00:38   961 25795028 transport.cpp:333] 192.168.1.10:5555: read thread spawning
scrcpy-ios I 11-11 20:00:38   961 25795029 transport.cpp:305] 192.168.1.10:5555: write thread spawning
scrcpy-ios I 11-11 20:00:38   961 25794791 adb.cpp:168] 192.168.1.10:5555: already offline
ERROR: Could not get local file path, using scrcpy-server from current directory
2023-11-11 20:00:46.142 scrcpy-ios[961:25794768] Show More Menu
2023-11-11 20:00:48.016 scrcpy-ios[961:25794768] LogPath: /var/mobile/Containers/Data/Application/AF213A1E-E91A-4279-B69D-17C350AF5D95/Documents/scrcpy@2023-11.log, Size: 5108
2023-11-11 20:00:48.019 scrcpy-ios[961:25794768] LogPath: /var/mobile/Containers/Data/Application/AF213A1E-E91A-4279-B69D-17C350AF5D95/Documents/scrcpy@2023-11.log, Size: 5284
2023-11-11 20:02:10.319 scrcpy-ios[961:25794768] <CATransformLayer: 0x280e20c60> - changing property backgroundColor in transform-only layer, will have no effect
2023-11-11 20:02:23.087 scrcpy-ios[961:25794768] -[_UIBarButtonItemData uiwindow]: unrecognized selector sent to instance 0x106f1eab0
2023-11-11 20:02:23.090 scrcpy-ios[961:25794768] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[_UIBarButtonItemData uiwindow]: unrecognized selector sent to instance 0x106f1eab0'
*** First throw call stack:
(0x1c0bf1e88 0x1b9f1b8d8 0x1c0d6684c 0x1c0c07fa0 0x1c0c70350 0x1053cb3dc 0x1053ce968 0x1053cec5c 0x1053ce560 0x1c0c1f404 0x1c0cc6474 0x1c0ca9724 0x1c0c33a08 0x1bb020ffc 0x1c390fe54 0x1c313c21c 0x1c315ca5c 0x1c30be6e8 0x1c3910a24 0x1c3077e80 0x1c3911720 0x1c3119318 0x1c31169d8 0x1c3115ddc 0x1c31155c0 0x1c3025508 0x1c3024a44 0x1c2fae308 0x1c2fab37c 0x1c368a184 0x1c3979ed8 0x1c81c1fdc 0x1c81c546c 0x1c81d8a58 0x1c81d0748 0x1c81d0444 0x1c0c826f8 0x1c0c64058 0x1c0c68ed4 0x1f9f6a368 0x1c31473d0 0x1c3147034 0x10544f2fc 0x1053f4d1c 0x1df2d0960)
INFO: Renderer: metal
DEBUG: Trilinear filtering disabled (not an OpenGL renderer)
DEBUG: Demuxer 'video': starting thread
DEBUG: Demuxer 'audio': starting thread
DEBUG: quit...
> pid=7563, success=true
> result:
[server] DEBUG: Screen streaming stopped
[server] DEBUG: Device message sender stopped
[server] DEBUG: Controller stopped
[server] ERROR: Audio encoding error
java.io.IOException: android.system.ErrnoException: write failed: EBADF (Bad file descriptor)
	at com.genymobile.scrcpy.IO.writeFully(IO.java:33)
	at com.genymobile.scrcpy.IO.writeFully(IO.java:40)
	at com.genymobile.scrcpy.Streamer.writeDisableStream(Streamer.java:61)
	at com.genymobile.scrcpy.AudioEncoder.encode(AudioEncoder.java:224)
	at com.genymobile.scrcpy.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-AudioEncoder(AudioEncoder.java:120)
	at com.genymobile.scrcpy.AudioEncoder$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:920)
Caused by: android.system.ErrnoException: write failed: EBADF (Bad file descriptor)
	at libcore.io.Linux.writeBytes(Native Method)
	at libcore.io.Linux.write(Linux.java:288)
	at libcore.io.ForwardingOs.write(ForwardingOs.java:946)
	at libcore.io.BlockGuardOs.write(BlockGuardOs.java:441)
	at android.system.Os.write(Os.java:1003)
	at com.genymobile.scrcpy.IO.writeFully(IO.java:25)
	... 6 more
[server] DEBUG: Audio encoder stopped
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalArgumentException: Failed to initialize video/hevc, error 0xfffffffe
	at android.media.MediaCodec.native_setup(Native Method)
	at android.media.MediaCodec.<init>(MediaCodec.java:1961)
	at android.media.MediaCodec.createEncoderByType(MediaCodec.java:1923)
	at com.genymobile.scrcpy.ScreenEncoder.createMediaCodec(ScreenEncoder.java:209)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:64)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:133)
	at com.genymobile.scrcpy.Server.main(Server.java:381)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:375)

> wait pid=7563, result=true
DEBUG: Server disconnected
DEBUG: Server terminated
ERROR: Could not get icon path
WARN: Could not load icon
ERROR: Demuxer 'video': stream disabled due to connection error
ERROR: Demuxer 'audio': stream disabled due to connection error
ERROR: Demuxer error
scrcpy-ios W 11-11 20:00:40   961 25794791 sockets.cpp:279] timeout expired while flushing socket, closing
libc++abi: terminating with uncaught exception of type NSException
2023-11-11 20:02:25.757 scrcpy-ios[967:25796428] Unbalanced calls to begin/end appearance transitions for <UIViewController: 0x106e0a000>.

**Comment by wsvn53** [comment]
Can you tell me your Android device model?

**Comment by joew8** [comment]
It's an Android simulator on Windows 10 called Noxplayer.

**Comment by wsvn53** [comment]
Are you using version 2.0? The issue on the Android simulator cannot connect should be solved in version 2.1

**Comment by joew8** [comment]
Oh, I didn't know there's a newer version on the app store. Version 2.1 works great! Thanks for your work and patience!
