### ISSUE TITLE
支持自定义audio-encoder

### ISSUE THREAD

**Issue by lzgzhyf** [wsvn53/scrcpy-mobile#47]
环境是redroid11，宿主机Ubuntu 22.04
客户端是iPhone 13，iOS 17.1
开启音频转发后，没有声音，日志有报错：
```
[server] ERROR: Exception on thread Thread[Thread-4,5,main]
java.lang.IllegalArgumentException: Failed to initialize audio/opus, error 0xfffffffe
	at android.media.MediaCodec.native_setup(Native Method)
	at android.media.MediaCodec.<init>(MediaCodec.java:1912)
	at android.media.MediaCodec.createEncoderByType(MediaCodec.java:1875)
	at com.genymobile.scrcpy.AudioEncoder.createMediaCodec(AudioEncoder.java:278)
	at com.genymobile.scrcpy.AudioEncoder.encode(AudioEncoder.java:174)
	at com.genymobile.scrcpy.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-AudioEncoder(AudioEncoder.java:120)
```
根据 Genymobile/scrcpy#3791
在Ubuntu上尝试`scrcpy --audio-encoder=aac`有声音

所以是否可以加上自定义audio-encoder的功能？

**Comment by lzgzhyf** [comment]
发现项目是支持通过URL Scheme的方式添加更多参数的，在URL Scheme中加上`&audio-codec=aac`即可

**Comment by ruanimal** [comment]
> 发现项目是支持通过URL Scheme的方式添加更多参数的，在URL Scheme中加上`&audio-codec=aac`即可

url scheme 参数填在什么地方呢？

![Image](https://github.com/user-attachments/assets/d40bc8cc-1316-4df4-8f52-e02df6a1d264)
